backend:
  jira:
    # baseURL of the JIRA server, this is usually just the host name
    baseURL:
    # user name of the JIRA account
    user:
    # password of the JIRA account
    password:
  archive:
    # location of the file that stores the archive
    archivePath:
    # optional time format string to print start and end times to the archive
    timeFormat:
tracker:
  # map of aliases for JQL queries; these can be used where a JQL query is
  # expected.
  queries:
    active: >-
      sprint in openSprints()
      and sprint not in futureSprints()
      and project=<project-name>
    all: >-
      project=<project-name>
  # location of the file that stores the local log
  statePath: ~/.track/state.log
  # default project prefix used for start command whenever only the issue
  # number is specified
  defaultProject:
  # map of aliases to issue keys
  issues:
  # time at which to truncate issues when calling the `close` command
  stopAt: 17:30
console:
  # aliases for command, e.g. 'track ls' is expanded to 'track search active'
  aliases:
    st: review
    ls: search active
